name: Build Kivy APK

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk python3-pip git \
            build-essential libffi-dev libssl-dev libsqlite3-dev libncurses5-dev \
            libncursesw5-dev libreadline6-dev libgdbm-dev libc6-dev libbz2-dev \
            libgl1-mesa-dev libgles2-mesa-dev libegl1-mesa-dev \
            libmtdev-dev xclip xsel libjpeg-dev zlib1g-dev \
            libfreetype6-dev liblcms2-dev libtiff5-dev libwebp-dev \
            automake autoconf libtool pkg-config \
            libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
            libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev \
            libjpeg-dev libcrypto++-dev
          python3 -m pip install --upgrade pip
          pip install buildozer cython

      - name: Set JAVA_HOME
        run: echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV

      - name: Install Android SDK Build Tools
        run: |
          mkdir -p $HOME/.android
          echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > $HOME/.android/repositories.cfg
          yes | sdkmanager --licenses
          yes | sdkmanager "platform-tools" "build-tools;30.0.3" "platforms;android-30"

      - name: Build APK
        run: |
          buildozer init || true
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SmartQR-debug.apk
          path: bin/*.apk